version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.17.1
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run build
          command: npm run build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
